### PR TITLE
[CARE-1572] Fix region locales incorrect routing

### PR DESCRIPTION
**Pull request by inf1nite-lo0p**
Unfortunately, the `returns correct language with same region` test still fails.

Given the following input as `languages` as an example:

1. `en_DE`
2. `de_DE`

Then `getLanguageFromNextLocaleIsoCode(languages, 'en')` should return `en_DE` but it returns `de_DE`.

But if I apply the same fix from my other PR the test will pass (#302) 👇

https://github.com/prezly/theme-kit-js/blob/dc13d7bb5f73f867e572235210c78ac292ebae39/packages/core/src/intl/languages.ts#L105-L116

### CODE REVIEW

**Comment by oleg-semyonov** [comment]
> Then getLanguageFromNextLocaleIsoCode(languages, 'en') should return en_DE but it returns de_DE.

This is what we discussed on the call - since `en_DE` is a default language, it shouldn't be referred to as `en` in any URLs. But I agree, this is still weird.

**Comment by MohammadxAli** [comment]
> since en_DE is a default language

In the tests, it wasn't tested as the default language:

https://github.com/prezly/theme-kit-js/blob/1a3b2fb93c35a9b615cd48fdf37ddb8446325348/packages/nextjs/src/__mocks__/languages.ts#L405-L414

https://github.com/prezly/theme-kit-js/blob/1a3b2fb93c35a9b615cd48fdf37ddb8446325348/packages/nextjs/src/__mocks__/languages.ts#L444-L453

That's why I thought it might break so many sites 🙂

**Comment by MohammadxAli** [comment]
Shall we merge and break everything? 🙂

**Comment by oleg-semyonov** [comment]
> Shall we merge and break everything? 🙂

I'd publish a preview version and test a couple sites with that, just to be sure

**Comment by MohammadxAli** [comment]
Unfortunately, I'm unable to release a preview version because of the internet situation and sanctions of NPM in my country:

```
? Are you sure you want to publish these packages? Yes
lerna info execute Skipping releases
lerna info git Pushing tags...
lerna info publish Publishing packages to npm...
lerna ERR! ECONNRESET request to https://registry.npmjs.org/@prezly%2ftheme-kit-core failed, reason: socket hang up
lerna ERR! FetchError: request to https://registry.npmjs.org/@prezly%2ftheme-kit-core failed, reason: socket hang up
lerna ERR!     at ClientRequest.<anonymous> (/home/mohammadxali/prezly/theme-kit-js/node_modules/npm-registry-fetch/node_modules/minipass-fetch/lib/index.js:130:14)
lerna ERR!     at ClientRequest.emit (node:events:513:28)
lerna ERR!     at TLSSocket.socketOnEnd (node:_http_client:526:9)
lerna ERR!     at TLSSocket.emit (node:events:525:35)
lerna ERR!     at endReadableNT (node:internal/streams/readable:1359:12)
lerna ERR! lerna request to https://registry.npmjs.org/@prezly%2ftheme-kit-core failed, reason: socket hang up
```

image


The tags are getting published here, but can't publish it to NPM registery.

**Comment by oleg-semyonov** [comment]
Oh, okay, I'll publish the version myself then, no worries!

**Pull request merged**
